[package]
authors = ["dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "https://docs.rs/sodiumoxide"
keywords = ["crypto", "NaCl", "libsodium"]
license = "MIT OR Apache-2.0"
name = "sodiumoxide"
readme = "README.md"
repository = "https://github.com/sodiumoxide/sodiumoxide"
categories = ["cryptography"]
version = "0.2.5"
exclude = [
    "**/.gitignore",
    ".travis.yml",
    "bors.toml"
]

[workspace]
members = ["libsodium-sys", "testcrate"]

[badges]
travis-ci = { repository = "sodiumoxide/sodiumoxide" }
appveyor = { repository = "Dylan-DPC/sodiumoxide", id = "u05iy6wufw9ncdi7" }
coveralls = { repository = "sodiumoxide/sodiumoxide" }

[dependencies]
libc = "0.2"
libsodium-sys = { version = "0.2.5", path = "libsodium-sys" }
serde = { version = "^1.0.59", default-features = false, optional = true }

[dev-dependencies]
serde = "^1.0.59"
serde_json = "^1.0.17"
rmp-serde = "^0.13.7"

[features]
benchmarks = []
std = []
default = ["serde", "std"]
use-pkg-config = ["libsodium-sys/use-pkg-config"]
